//! Raw FFI bindings to the nigiri C ABI.
//!
//! These bindings are auto-generated by bindgen from `include/nigiri/abi.h`.
//! All types and functions here are unsafe and require manual memory management
//! via the corresponding `nigiri_destroy_*` functions.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
